### ISSUE TITLE
Decide technologies

### ISSUE THREAD

**Issue by Toto-hitori** [Arquisoft/wiq_en2b#2]

**Comment by jjgancfer** [comment]
Currently, we are working with Java Spring Boot for the backend and React for the frontend. For the database we'll use PostgreSQL.

**Comment by uo283928** [comment]
[Moved from issue #6 to #2, where it was supposed to be writen originally.]
This is a bit long as an answer but I tried to simplify and make as clear as possible.
I have been researching a bit on the different approaches we can choose in order to query from Wikidata.
# Spring Boot:
## This is some info about most of the libraries:
They are plenty and all of them seem to use REST to query the data from wikidata's endpoint. Also, as far as I am concerned, all of them use JDBC for querying. However, due to volume I have not check on every one.
### ✅ Pros (for most of the libraries):
+ Many file formats available (json, csv, xml,...)
+ Well documented
+ Allow parameterized queries
### ❌ Cons:
   - A minute of processing time is granted per minute and per IP and 30 error queries per minute
## If using [Jena](https://github.com/SmartDataAnalytics/jena-sparql-api/blob/master/README.md), which seems to be the most important library out there regarding SPARQL:
First, it also uses REST so the previous point will be likely to be applied here too. It provides a library to connect to Jena SPARQL API which has lots of different capabilities.
### ✅ Pros:
   + It has a RDF (format which can be queried via SPARQL) mapper which is based on JPA so they both look alike.
    + It provides an endpoint called sparqlify which is a rewritter from SPARQL to SQL. Its main features are:
        + Supports JPA
        + It is available on PostgreSQL
        + It can be set so it automically simplifies queries for better performance
  + Adds another [possible syntax for querying](https://jena.apache.org/documentation/query/manipulating_sparql_using_arq.html), which seems optional and well documented. However, I have not researched enough enough about it (I will do if you guys think it is an interesting option). It is based on algebra.
  + Allows query transformations
  + Provides code for implementing our own SPARQL endpoint
# Node.js
Regarding Node.js, there are few libraries available which have not been updated in some years. It is way simpler as it is basically an HTTP request in js.

**Comment by jjgancfer** [comment]
Since we are starting to create more issues related to the technologies (see #11 and #12, for instance) marked as duplicate and closed.
