### ISSUE TITLE
Self Report: First delivery

### ISSUE THREAD

**Issue by UO283615** [Arquisoft/wiq_en2b#39]
This issue is for the self reports of the first delivery.

**Comment by UO283615** [comment]
I wrote the second part of the documentation and took in writing the eighth part #31.
I also took part on several discussions about the architecture and design of the project, that can be seen in the [minutes of meetings](https://github.com/Arquisoft/wiq_en2b/wiki).
Lastly, I helped clear up the readme #38

**Comment by gony02** [comment]
For this delivery I worked on:
### Pull requests 🪢
I have made a pull request and have reviewed several.
- #36

### Issues ✍️
- #6
- #16
- #19
- #28

### Wiki 📖
Moreover, I have written several pages on the Wiki and I also participated in all the meetings.

- [Minutes 1](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-01-30-2024-laboratory-session)
- [Minutes 2](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-02-02-2024-frontend-meeting)
- [Minutes 3](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-04-02-2024-meeting)
- [Minutes 4](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-06-02-2024-laboratory-session)
- [Minutes 5](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-11-02-2024-meeting)
- [Minutes 6](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-13-02-2024-laboratory-session)
- [Minutes 7](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-18-02-2024-meeting)

### Other 👨‍💻
I was also studying how to use [React](https://react.dev/learn) and [Chakra UI](https://chakra-ui.com/). Simultaneously, I've been contributing to the development of a well-organized repository.

**Comment by sergiorodriguezgarcia** [comment]
In this delivery I have made two sections from the documentation that have been added in the following pull request:

- https://github.com/Arquisoft/wiq_en2b/pull/34

Then, I worked on some issues proposed in the repository:

- https://github.com/Arquisoft/wiq_en2b/issues/30
- https://github.com/Arquisoft/wiq_en2b/issues/29
- https://github.com/Arquisoft/wiq_en2b/issues/27
- https://github.com/Arquisoft/wiq_en2b/issues/16

**Comment by Toto-hitori** [comment]
For this delivery I worked on:
### Pull requests 🪢
I wrote the documentation for part 3 and part of part 7.

- #33
- #41 

I also rewrote the authentication and user management API using Java SpringBoot 3.

- #17 

### Issues ✍️
- #2 
- #4
- #5
- #15 
- #21 
- #25 

### Wiki 📖
I have participated in the following meetings:

- [Minutes 1](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-01-30-2024-laboratory-session)
- [Minutes 3](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-04-02-2024-meeting)
- [Minutes 4](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-06-02-2024-laboratory-session)
- [Minutes 5](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-11-02-2024-meeting)
- [Minutes 6](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-13-02-2024-laboratory-session)
- [Minutes 7](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-18-02-2024-meeting)

### Other 👨‍💻
- I have worked on the [Notion documentation]( https://www.notion.so/ASW-052c253414ee4895afbe08b7ef943106), where I am in the process of writing a guide with development instructions for the backend developers.
- Currently I am working on a Dockerfile and new Github actions for the SpringBoot API as well as reading a book about Unit Testing to start writing tests for the already existing endpoints.

**Comment by jjgancfer** [comment]
For this delivery I have worked on:
## Pull requests 🪢

My own pull requests during the last three weeks are the following:
- #9 
- #14 
- #32 
- #35 
- #40 

I have also reviewed the following ones:

- #7 
- #17 
- #31 
- #33
- #34 
- #38

## Issues ✍️

- #2
- #6 
- #11  
- #13 
- #16 

## Wiki 📖

Moreover, I have written the minutes for the first session (later edited by @gony02) and I also have participated in all the meetings we have had.

- [Minutes 1](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-01-30-2024-laboratory-session)
- [Minutes 2](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-02-02-2024-frontend-meeting)
- [Minutes 3](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-04-02-2024-meeting)
- [Minutes 4](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-06-02-2024-laboratory-session)
- [Minutes 5](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-11-02-2024-meeting)
- [Minutes 6](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-13-02-2024-laboratory-session)
- [Minutes 7](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-18-02-2024-meeting)

## Other 👨‍💻

I have also looked into using Next.js or page template frameworks instead of React (with React Router) for the webapp, and trying to integrate the last Typescript version into the project (something that did not work in the end).

**Comment by uo283928** [comment]
For this delivery I worked on:
# Pull requests 🪢
I wrote the documentation for [part 6] (https://github.com/Arquisoft/wiq_en2b/issues/24) and the final chunk of [part 8] (https://github.com/Arquisoft/wiq_en2b/issues/26).

# Issues ✍️
- #6 
- #11 
- #16 


# Wiki 📖

I have participated in the following meetings:

- [Minutes 1](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-01-30-2024-laboratory-session)
- [Minutes 3](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-04-02-2024-meeting)
- [Minutes 4](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-06-02-2024-laboratory-session)
- [Minutes 6](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-13-02-2024-laboratory-session)
- [Minutes 7](https://github.com/Arquisoft/wiq_en2b/wiki/Minutes-for-the-18-02-2024-meeting)

# Other 👨‍💻

I mainly searched for information about Wikidata and possible ways to implement the Question Generator component:
- I first searched about Wikidata Query Service and RDF.
- Then, I looked at SPARQL.
- Finding possibilitites for Springboot and Node.js
- Searching for repositories and documentation about them.

**Comment by UO283615** [comment]
Closing it as the review has finished
